## Importação das bibliotecas

In [1]:
import sqlalchemy
import mysql.connector
import pandas as pd

## Ingestão de dados

Criando a conexão com o banco de dados MySQL

In [2]:
eng = sqlalchemy.create_engine('mysql+mysqlconnector://looqbox-challenge:looq-challenge@35.199.115.174/looqbox-challenge')

Criando o DataFrame

In [3]:
query_1 = """
SELECT
      STORE_CODE,
      STORE_NAME,
      START_DATE,
      END_DATE,
      BUSINESS_NAME,
      BUSINESS_CODE
FROM data_store_cad
"""

query_2 = """
SELECT
        STORE_CODE,
        DATE,
        SALES_VALUE,
        SALES_QTY
FROM data_store_sales
WHERE DATE BETWEEN '2019-01-01' AND '2019-12-31'
"""

df_1 = pd.read_sql(query_1, con=eng)
df_2 = pd.read_sql(query_2, con=eng)

Mesclando as queries

In [4]:
df = df_2.join(df_1, on='STORE_CODE', how='left', lsuffix='.dss')
df.head()

,STORE_CODE.dss,DATE,SALES_VALUE,SALES_QTY,STORE_CODE,STORE_NAME,START_DATE,END_DATE,BUSINESS_NAME,BUSINESS_CODE
0,1,2019-01-01,196623.22,12838,2.0,Chicago,2007-10-01,,Varejo,1.0
1,10,2019-01-01,126795.44,4933,11.0,Rio de Janeiro,2019-01-01,,Farma,4.0
2,11,2019-01-01,223937.00,7724,12.0,Madri,2019-01-01,,Farma,4.0
3,12,2019-01-01,200251.80,7043,13.0,Dubai,2019-01-01,,Atacado,5.0
4,13,2019-01-01,196623.22,12838,14.0,Bahia,2019-01-01,,Atacado,5.0

Tratamento e filtragem dos dados

In [5]:
df['DATE'] = pd.to_datetime(df['DATE'])

df = df[df['DATE'] >= '2019-10-01']

Sumarização dos dados

In [6]:
df = df.groupby(['STORE_NAME', 'BUSINESS_NAME'])[['SALES_VALUE', 'SALES_QTY']].sum().reset_index()
df = df.rename(columns={
                        'STORE_NAME': 'Loja',
                        'BUSINESS_NAME': 'Categoria',
                        'SALES_VALUE': 'Valor',
                        'SALES_QTY': 'Quantidade',
                        })

df.head()

           Loja    Categoria        Valor  Quantidade
0         Bahia      Atacado  21213088.57     1378476
1       Bangkok        Posto   8376271.00      612968
2         Belem  Proximidade  21213088.57     1378476
3        Berlin  Proximidade  21213088.57     1378476
4  Buenos Aires      Atacado  21213088.57     1378476

Criando a coluna de Ticket Médio

In [9]:
df['TM'] = round(df['Valor']/df['Quantidade'],2)

df[['Loja', 'Categoria', 'TM']]

              Loja    Categoria     TM
0            Bahia      Atacado  15.39
1          Bangkok        Posto  13.67
2            Belem  Proximidade  15.39
3           Berlin  Proximidade  15.39
4     Buenos Aires      Atacado  15.39
5          Chicago       Varejo  15.39
6            Dubai      Atacado  29.03
7        Hong Kong        Farma  28.99
8           London        Farma  15.37
9            Madri        Farma  29.59
10           Miami        Posto  13.67
11        New York  Proximidade  15.39
12           Paris  Proximidade  15.39
13  Rio de Janeiro        Farma  26.35
14            Roma       Varejo  15.53
15        Salvador      Atacado  15.39
16          Sidney        Posto  15.39
17           Tokio       Varejo  15.39
18       Vancouver        Posto  13.67